author: b3n3dkt
name: Game1v1
version: 1.0.0
main: de.rasorsystems.game1v1.Game1v1
api-version: 1.8

commands:
   setspawn:
   spawn:
   createworld:
   deleteworld:
   startgame:
   setup:
   setupconfirm: